# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/hlznl/Desktop/GAME/vivado/Basys3_GAME/Basys3_GAME.cache/wt [current_project]
set_property parent.project_path C:/Users/hlznl/Desktop/GAME/vivado/Basys3_GAME/Basys3_GAME.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/hlznl/Desktop/GAME/vivado/Basys3_GAME/Basys3_GAME.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/hlznl/Desktop/GAME/rtl/baud_rate_gen.v
  C:/Users/hlznl/Desktop/GAME/rtl/bcd_converter.v
  C:/Users/hlznl/Desktop/GAME/rtl/block_mem.v
  C:/Users/hlznl/Desktop/GAME/rtl/collision_ctl.v
  C:/Users/hlznl/Desktop/GAME/rtl/draw_end.v
  C:/Users/hlznl/Desktop/GAME/rtl/draw_health.v
  C:/Users/hlznl/Desktop/GAME/rtl/draw_score.v
  C:/Users/hlznl/Desktop/GAME/rtl/egg_ctl.v
  C:/Users/hlznl/Desktop/GAME/rtl/egg_mem.v
  C:/Users/hlznl/Desktop/GAME/rtl/end_mem.v
  C:/Users/hlznl/Desktop/GAME/rtl/floors.v
  C:/Users/hlznl/Desktop/GAME/rtl/game_ctl.v
  C:/Users/hlznl/Desktop/GAME/rtl/ghost_background_mem.v
  C:/Users/hlznl/Desktop/GAME/rtl/ghost_bottom.v
  C:/Users/hlznl/Desktop/GAME/rtl/ghost_top.v
  C:/Users/hlznl/Desktop/GAME/rtl/grounded.v
  C:/Users/hlznl/Desktop/GAME/rtl/heart_mem.v
  C:/Users/hlznl/Desktop/GAME/rtl/mad_ghost.v
  C:/Users/hlznl/Desktop/GAME/rtl/mad_ghost_mem.v
  C:/Users/hlznl/Desktop/GAME/rtl/numbers_mem.v
  C:/Users/hlznl/Desktop/GAME/rtl/standard_ghost_mem.v
  C:/Users/hlznl/Desktop/GAME/rtl/tick_gen.v
  C:/Users/hlznl/Desktop/GAME/rtl/uart_ctl.v
  C:/Users/hlznl/Desktop/GAME/rtl/uart_read.v
  C:/Users/hlznl/Desktop/GAME/rtl/uart_receiver.v
  C:/Users/hlznl/Desktop/GAME/rtl/uart_transmitter.v
  C:/Users/hlznl/Desktop/GAME/rtl/uart_write.v
  C:/Users/hlznl/Desktop/GAME/rtl/vga_timing.v
  C:/Users/hlznl/Desktop/GAME/rtl/wall_mem.v
  C:/Users/hlznl/Desktop/GAME/rtl/yoshi_mem.v
  C:/Users/hlznl/Desktop/GAME/rtl/yoshi_mem_2.v
  C:/Users/hlznl/Desktop/GAME/rtl/yoshi_soul_mem.v
  C:/Users/hlznl/Desktop/GAME/rtl/yoshi_sprite.v
  C:/Users/hlznl/Desktop/GAME/rtl/yoshi_sprite_2.v
  C:/Users/hlznl/Desktop/GAME/rtl/module_top.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/hlznl/Desktop/GAME/rtl/PS2.vhd
  C:/Users/hlznl/Desktop/GAME/rtl/debouncer.vhd
  C:/Users/hlznl/Desktop/GAME/rtl/keycode_to_ascii.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/hlznl/Desktop/GAME/vivado/Basys3_GAME/Basys3_GAME.srcs/constrs_1/imports/source/module_top.xdc
set_property used_in_implementation false [get_files C:/Users/hlznl/Desktop/GAME/vivado/Basys3_GAME/Basys3_GAME.srcs/constrs_1/imports/source/module_top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top display_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef display_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file display_top_utilization_synth.rpt -pb display_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
